---
title:
output: 
  html_document: 
    theme: spacelab
    toc: false
---
```{r, include = FALSE}
library(knitr)
library(bonsai)
knit_theme$set("default")
options(digits = 3)
palette(palette)
```
```{r global_options, include = FALSE}
knitr::opts_chunk$set(dev="png")
```
#[primates HKY Gamma one chain](_main_bonsai_page.html)

##[Diagnostics](flags.html)

##[Numerical parameters](numeric_parameters.html)

[Posterior](Posterior_bonsai_page.html), 
Likelihood, 
[Prior](Prior_bonsai_page.html), 
[alpha](alpha_bonsai_page.html), 
[beta](beta_bonsai_page.html), 
[diversification](diversification_bonsai_page.html), 
[extinction](extinction_bonsai_page.html), 
[gamma_rates[1]](gamma_rates[1]_bonsai_page.html), 
[gamma_rates[2]](gamma_rates[2]_bonsai_page.html), 
[gamma_rates[3]](gamma_rates[3]_bonsai_page.html), 
[gamma_rates[4]](gamma_rates[4]_bonsai_page.html), 
[kappa](kappa_bonsai_page.html), 
[pi[1]](pi[1]_bonsai_page.html), 
[pi[2]](pi[2]_bonsai_page.html), 
[pi[3]](pi[3]_bonsai_page.html), 
[pi[4]](pi[4]_bonsai_page.html), 
[root](root_bonsai_page.html), 
[speciation](speciation_bonsai_page.html), 
[turnover](turnover_bonsai_page.html)

#### Posterior distribution
```{r, echo = FALSE, include = TRUE, fig.align="center", fig.height = 3 }
par(las = 2, oma=c(0,0,0,0),mar=0.1+c(5,4,4,0))
layout.matrix <- matrix(1:3,nrow=1,byrow=TRUE)
layout(layout.matrix)
parameters[["Likelihood"]]$traces()
parameters[["Likelihood"]]$densities()
parameters[["Likelihood"]]$boxplots()
```

```{r, echo = FALSE}
kable(parameters[["Likelihood"]]$summaryTable(),booktabs=TRUE,row.names=TRUE)
```

#### Prior distribution
```{r, echo = FALSE, include = TRUE, fig.align="center", fig.height = 3 }
par(las = 2, oma=c(0,0,0,0),mar=0.1+c(5,4,4,0))
layout.matrix <- matrix(1:3,nrow=1,byrow=TRUE)
layout(layout.matrix)
parameters[["Likelihood"]]$traces(posterior=FALSE)
parameters[["Likelihood"]]$densities(posterior=FALSE)
parameters[["Likelihood"]]$boxplots(posterior=FALSE)
```

```{r, echo = FALSE}
kable(parameters[["Likelihood"]]$summaryTable(posterior=FALSE),booktabs=TRUE,row.names=TRUE)
```

##[Clade parameters](clade_parameters.html)

